version: "3.8"

services:
  back:
    build: ./backend
    volumes:
      - ./backend:/app
    tty: true
    depends_on:
      - db
    ports:
      - 8080:8080

  front:
    container_name: front
    build:
      context: ./frontend
      dockerfile: Dockerfile
    tty: true
    ports:
      - 3000:3000
      - 6006:6006
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules

  db:
    build: ./db
    restart: always

    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: user
      POSTGRES_DB: test

    ports:
      - 5432:5432

volumes:
  node_modules: {}
