version: "3.8"

services:
  back:
    container_name: bookhoarder-back
    build: ./backend
    volumes:
      - ./backend:/app
    tty: true
    depends_on:
      - db
    ports:
      - 8080:8080
        
    env_file:
      - ./backend/.local.env

  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules

  storybook:
    build:
      context: ./frontend
      dockerfile: Dockerfile.storybook
    tty: true
    ports:
      - 6006:6006
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    command: pnpm storybook

  db:
    container_name: bookhoarder-db
    build: ./db
    restart: always
    
    ports:
      - 5432:5432

    env_file:
      - ./db/.local.env

volumes:
  node_modules: {}
