version: "3.8"

services:
  back:
    container_name: bookhoarder-back
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - ./openapi_schema:/openapi
    tty: true
    depends_on:
      - db
    ports:
      - 8080:8080

    env_file:
      - ./backend/.local.env

  swagger:
    container_name: bookhoarder-swagger
    build:
      context: ./openapi_schema
      dockerfile: Dockerfile.swagger
    tty: true

    environment:
      - SWAGGER_JSON=/openapi/openapi.yaml
    volumes:
      - ./openapi_schema:/openapi

    ports:
      - "8001:8080"

  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - ./openapi_schema:/openapi_schema
      - node_modules:/app/node_modules

  storybook:
    build:
      context: ./frontend
      dockerfile: Dockerfile.storybook
    tty: true
    ports:
      - 6006:6006
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    command: pnpm storybook

  db:
    build:
      context: ./db
      dockerfile: Dockerfile

    restart: always

    ports:
      - 5432:5432

    env_file:
      - ./db/.local.env

volumes:
  node_modules: {}
