openapi: 3.0.0
info:
  title: BookHoarder API
  description: description
  version: 0.0.1
  
servers:
  - url: http://localhost:8080
    description: dev server
  
paths:
  /books:
    $ref: "./paths/books.yaml"
  /tags:
    $ref: "./paths/tags.yaml"
  /books/{bookId}:
    $ref: "./paths/books_bookId.yaml"    
  /{userId}/books/{bookId}:
    $ref: "./paths/userId_books_bookId.yaml"
  /{userId}/hoarder:
    $ref: "./paths/userId_hoarder.yaml" 
  /{userId}/hoarder/{bookId}:
    $ref: "./paths/userId_hoarder_bookId.yaml"
  /{userId}/tags:
    $ref: "./paths/userId_tags.yaml"
  /{userId}/tags/{tagId}:
    $ref: "./paths/userId_tags_tagId.yaml"