name: frontend ci
on:
    pull_request:
        types: [opened, reopened, synchronize, ready_for_review]

env:
    WORKING_DIRECTORY: frontend

jobs:
    lint:
        runs-on: ubuntu-24.04
        if: ${{ !(!contains(github.head_ref, 'frontend')) && !endsWith(github.head_ref, 'back-only') && !endsWith(github.head_ref, 'no-code') }}
        defaults:
            run:
              working-directory: ${{ env.WORKING_DIRECTORY }}
        steps:
        - uses: actions/checkout@v4
        - uses: pnpm/action-setup@v2.2.2
          with:
            version: $(cat package.json | jq -r '.volta.pnpm')
        - run: pnpm i --frozen-lockfile
        - run: pnpm run lint
    ci:
        runs-on: ubuntu-24.04
        if: ${{ !(!contains(github.head_ref, 'frontend')) && !endsWith(github.head_ref, 'back-only') && !endsWith(github.head_ref, 'no-code') }}
        defaults:
            run:
              working-directory: ${{ env.WORKING_DIRECTORY }}
        steps:
        - uses: actions/checkout@v4
        - uses: pnpm/action-setup@v2.2.2
          with:
            version: $(cat package.json | jq -r '.volta.pnpm')
        - run: pnpm i --frozen-lockfile
        - run: pnpm test

